//These control the damage thresholds for the various ways of removing limbs
#define DROPLIMB_THRESHOLD_EDGE 5
#define DROPLIMB_THRESHOLD_TEAROFF 2
#define DROPLIMB_THRESHOLD_DESTROY 1

#define DROPLIMB_CUMULATIVE_TEAROFF	0.9
#define DROPLIMB_CUMULATIVE_DESTROY	1.25

#define ORGAN_RECOVERY_THRESHOLD (5 MINUTES)