-- MySQL Script generated by MySQL Workbench
-- Sun Jul 11 17:47:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`credit_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`credit_records` (
  `character_id` INT UNSIGNED NOT NULL,
  `credits` INT ZEROFILL NOT NULL DEFAULT 0,
  PRIMARY KEY (`character_id`),
  UNIQUE INDEX `character_id_UNIQUE` (`character_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`credit_lastround`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`credit_lastround` (
  `character_id` INT UNSIGNED NOT NULL,
  `credits_stored` INT ZEROFILL NOT NULL DEFAULT 0,
  `credits_carried` INT ZEROFILL NOT NULL DEFAULT 0,
  `character_status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`character_id`),
  UNIQUE INDEX `character_id_UNIQUE` (`character_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`characters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`characters` (
  `character_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ckey` VARCHAR(30) NOT NULL,
  `character_name` VARCHAR(26) NOT NULL,
  `birth` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `last_seen` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`character_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`store_schematics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`store_schematics` (
  `store_schematic` VARCHAR(45) NULL,
  `upload_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `store_schematic_UNIQUE` (`store_schematic` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
