-- MySQL Script generated by MySQL Workbench
-- Thu Jul  1 02:59:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`credit_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`credit_records` (
  `character_id` INT UNSIGNED NOT NULL,
  `credits` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`character_id`),
  UNIQUE INDEX `character_id_UNIQUE` (`character_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`credit_lastround`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`credit_lastround` (
  `character_id` INT UNSIGNED NOT NULL,
  `credits_stored` INT ZEROFILL NOT NULL,
  `credits_carried` INT NULL,
  `status` INT NULL DEFAULT 0,
  PRIMARY KEY (`character_id`),
  UNIQUE INDEX `character_id_UNIQUE` (`character_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`death`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`death` (
  `id` INT(11) NOT NULL,
  `pod` TEXT NOT NULL COMMENT 'Place of death',
  `coord` TEXT NOT NULL COMMENT 'X, Y, Z POD',
  `tod` DATETIME NOT NULL COMMENT 'Time of death',
  `job` TEXT NOT NULL,
  `special` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `byondkey` TEXT NOT NULL,
  `laname` TEXT NOT NULL COMMENT 'Last attacker name',
  `lakey` TEXT NOT NULL COMMENT 'Last attacker key',
  `gender` TEXT NOT NULL,
  `bruteloss` INT(11) NOT NULL,
  `brainloss` INT(11) NOT NULL,
  `fireloss` INT(11) NOT NULL,
  `oxyloss` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`erro_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`erro_admin` (
  `id` INT(11) NOT NULL,
  `ckey` VARCHAR(32) NOT NULL,
  `rank` VARCHAR(32) NOT NULL DEFAULT 'Administrator',
  `level` INT(2) NOT NULL DEFAULT '0',
  `flags` INT(16) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`erro_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`erro_admin_log` (
  `id` INT(11) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `adminckey` VARCHAR(32) NOT NULL,
  `adminip` VARCHAR(18) NOT NULL,
  `log` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`erro_ban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`erro_ban` (
  `id` INT(11) NOT NULL,
  `bantime` DATETIME NOT NULL,
  `serverip` VARCHAR(32) NOT NULL,
  `bantype` VARCHAR(32) NOT NULL,
  `reason` TEXT NOT NULL,
  `job` VARCHAR(32) NULL DEFAULT NULL,
  `duration` INT(11) NOT NULL,
  `rounds` INT(11) NULL DEFAULT NULL,
  `expiration_time` DATETIME NOT NULL,
  `ckey` VARCHAR(32) NOT NULL,
  `computerid` VARCHAR(32) NOT NULL DEFAULT '',
  `ip` VARCHAR(32) NOT NULL DEFAULT '',
  `a_ckey` VARCHAR(32) NOT NULL,
  `a_computerid` VARCHAR(32) NOT NULL DEFAULT '',
  `a_ip` VARCHAR(32) NOT NULL DEFAULT '',
  `who` TEXT NOT NULL,
  `adminwho` TEXT NOT NULL,
  `edits` TEXT NULL DEFAULT NULL,
  `unbanned` TINYINT(1) NULL DEFAULT NULL,
  `unbanned_datetime` DATETIME NULL DEFAULT NULL,
  `unbanned_ckey` VARCHAR(32) NULL DEFAULT NULL,
  `unbanned_computerid` VARCHAR(32) NULL DEFAULT NULL,
  `unbanned_ip` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`erro_feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`erro_feedback` (
  `id` INT(11) NOT NULL,
  `time` DATETIME NOT NULL,
  `round_id` INT(8) NOT NULL,
  `var_name` VARCHAR(32) NOT NULL,
  `var_value` INT(16) NULL DEFAULT NULL,
  `details` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`erro_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`erro_player` (
  `id` INT(11) NOT NULL,
  `ckey` VARCHAR(32) NOT NULL,
  `firstseen` DATETIME NOT NULL,
  `lastseen` DATETIME NOT NULL,
  `ip` VARCHAR(18) NOT NULL,
  `computerid` VARCHAR(32) NOT NULL,
  `lastadminrank` VARCHAR(32) NOT NULL DEFAULT 'Player',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ckey` (`ckey` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`erro_poll_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`erro_poll_option` (
  `id` INT(11) NOT NULL,
  `pollid` INT(11) NOT NULL,
  `text` VARCHAR(255) NOT NULL,
  `percentagecalc` TINYINT(1) NOT NULL DEFAULT '1',
  `minval` INT(3) NULL DEFAULT NULL,
  `maxval` INT(3) NULL DEFAULT NULL,
  `descmin` VARCHAR(32) NULL DEFAULT NULL,
  `descmid` VARCHAR(32) NULL DEFAULT NULL,
  `descmax` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`erro_poll_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`erro_poll_question` (
  `id` INT(11) NOT NULL,
  `polltype` VARCHAR(16) NOT NULL DEFAULT 'OPTION',
  `starttime` DATETIME NOT NULL,
  `endtime` DATETIME NOT NULL,
  `question` VARCHAR(255) NOT NULL,
  `adminonly` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`erro_poll_textreply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`erro_poll_textreply` (
  `id` INT(11) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `pollid` INT(11) NOT NULL,
  `ckey` VARCHAR(32) NOT NULL,
  `ip` VARCHAR(18) NOT NULL,
  `replytext` TEXT NOT NULL,
  `adminrank` VARCHAR(32) NOT NULL DEFAULT 'Player',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`erro_poll_vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`erro_poll_vote` (
  `id` INT(11) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `pollid` INT(11) NOT NULL,
  `optionid` INT(11) NOT NULL,
  `ckey` VARCHAR(255) NOT NULL,
  `ip` VARCHAR(16) NOT NULL,
  `adminrank` VARCHAR(32) NOT NULL,
  `rating` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`erro_privacy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`erro_privacy` (
  `id` INT(11) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `ckey` VARCHAR(32) NOT NULL,
  `option` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`library` (
  `id` INT(11) NOT NULL,
  `author` TEXT NOT NULL,
  `title` TEXT NOT NULL,
  `content` TEXT NOT NULL,
  `category` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`population`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`population` (
  `id` INT(11) NOT NULL,
  `playercount` INT(11) NULL DEFAULT NULL,
  `admincount` INT(11) NULL DEFAULT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`ranks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`ranks` (
  `Rank` INT(11) NOT NULL COMMENT 'What Numeric Rank',
  `Desc` TEXT NOT NULL COMMENT 'What is a person with this rank?',
  PRIMARY KEY (`Rank`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database`.`whitelist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`whitelist` (
  `id` INT(11) NOT NULL,
  `ckey` TEXT NOT NULL,
  `race` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`characters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`characters` (
  `character_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ckey` VARCHAR(30) NOT NULL,
  `character_name` VARCHAR(26) NOT NULL,
  `birth` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `last_seen` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`character_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
