GLOBAL_LIST_INIT(organ_parents, list(BP_L_FOOT = BP_L_LEG,
BP_R_FOOT = BP_R_LEG,
BP_R_LEG = BP_GROIN,
BP_L_LEG = BP_GROIN,
BP_TAIL = BP_GROIN,
BP_GROIN = BP_CHEST,
BP_HEAD = BP_CHEST,
BP_L_ARM = BP_CHEST,
BP_R_ARM = BP_CHEST,
BP_L_HAND = BP_L_ARM,
BP_R_HAND = BP_R_ARM,
BP_EYES = BP_HEAD,
BP_MOUTH = BP_HEAD))

GLOBAL_LIST_INIT(key_to_mob, list())

GLOBAL_LIST_INIT(players, list())