#include "Aegis_areas.dm"
#include "deadspace_shuttles.dm"
#include "ishimura.dm"
#include "ishimura_announcements.dm"
#include "Ishimura_areas.dm"
#include "ishimura_presets.dm"
#include "Space_areas.dm"
#include "M.01 Ishimura (L).dmm"
#include "M.02 Ishimura (M).dmm"
#include "M.03 Ishimura (U).dmm"
#include "M.04 Aegis VII.dmm"
#include "M.05 Space.dmm"
#include "code\structures\executive_shuttle.dm"
#include "code\structures\items.dm"
#include "maps\DeadSpace\code\structures\structures.dm"